### ISSUE TITLE
2.0: consider removing the base icon fonts

### ISSUE THREAD

**Issue by kotyy** [Staplegun-US/site-start#20]

**Comment by alkrauss48** [comment]
I personally use the base icon fonts a lot. It's helpful if we have a small project where the only icons we need are some simple ones like facebook, twitter, youtube, email, maybe some arrows, etc. Even if it's on a big project that has custom icons, we may still have to create some icons, but we don't have to worry about facebook, etc.

If the issue is to not include any extraneous CSS, then I'd be okay with commenting out the import line for `base-icon-fonts.scss` by default, and uncommenting it as needed. Does that work?
